-- MySQL Script generated by MySQL Workbench
-- Sun Dec 20 23:38:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema web
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web` DEFAULT CHARACTER SET utf8 ;
USE `web` ;

-- -----------------------------------------------------
-- Table `web`.`nazva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`nazva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazva_tovaru` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`kod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`kod` (
  `idkod` INT UNSIGNED NOT NULL,
  `kod_tovaru` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`vyd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`vyd` (
  `idvyd` INT UNSIGNED NOT NULL,
  `vyd_tovaru` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idvyd`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`srok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`srok` (
  `idsrok` INT NOT NULL,
  `srok_godnosti` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsrok`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`firma` (
  `idfirma` INT UNSIGNED NOT NULL,
  `firma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfirma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `web`.`zagalna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web`.`zagalna` (
  `idzagalna` INT NOT NULL AUTO_INCREMENT,
  `nazva_tovaru` VARCHAR(45) NOT NULL,
  `kod` VARCHAR(45) NOT NULL,
  `vyd` VARCHAR(45) NOT NULL,
  `firma` VARCHAR(45) NOT NULL,
  `data_vygotovlena` DATE NOT NULL,
  `srok_gognosty` VARCHAR(45) NOT NULL,
  `cina` VARCHAR(45) NOT NULL,
  `nazva_id` INT NOT NULL,
  `kod_idkod` INT UNSIGNED NOT NULL,
  `vyd_idvyd` INT UNSIGNED NOT NULL,
  `srok_idsrok` INT NOT NULL,
  `firma_idfirma` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idzagalna`),
  INDEX `fk_zagalna_nazva1_idx` (`nazva_id` ASC) VISIBLE,
  INDEX `fk_zagalna_kod1_idx` (`kod_idkod` ASC) VISIBLE,
  INDEX `fk_zagalna_vyd1_idx` (`vyd_idvyd` ASC) VISIBLE,
  INDEX `fk_zagalna_srok1_idx` (`srok_idsrok` ASC) VISIBLE,
  INDEX `fk_zagalna_firma1_idx` (`firma_idfirma` ASC) VISIBLE,
  CONSTRAINT `fk_zagalna_nazva1`
    FOREIGN KEY (`nazva_id`)
    REFERENCES `web`.`nazva` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zagalna_kod1`
    FOREIGN KEY (`kod_idkod`)
    REFERENCES `web`.`kod` (`idkod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zagalna_vyd1`
    FOREIGN KEY (`vyd_idvyd`)
    REFERENCES `web`.`vyd` (`idvyd`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zagalna_srok1`
    FOREIGN KEY (`srok_idsrok`)
    REFERENCES `web`.`srok` (`idsrok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zagalna_firma1`
    FOREIGN KEY (`firma_idfirma`)
    REFERENCES `web`.`firma` (`idfirma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
